import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const genericWorkoutMetRows = [
  { workoutType: 'Running', avgMetPerHour: 8.4, minMet: 2.2, maxMet: 16.4, mlp: null, maxMetLimit: 13, metCap: 10.5 },
  { workoutType: 'Gym(Cardio)', avgMetPerHour: 6.9, minMet: 3.4, maxMet: 13.4, mlp: null, maxMetLimit: 11.8, metCap: 10 },
  { workoutType: 'Biking', avgMetPerHour: 5.8, minMet: 3.0, maxMet: 12.0, mlp: null, maxMetLimit: 10.9, metCap: 10 },
  { workoutType: 'Gym(Specialist)', avgMetPerHour: null, minMet: null, maxMet: null, mlp: null, maxMetLimit: null, metCap: 10 },
  { workoutType: 'Gym(Strength Training)', avgMetPerHour: null, minMet: null, maxMet: null, mlp: null, maxMetLimit: null, metCap: 9 },
  { workoutType: 'Racket Sports', avgMetPerHour: 8.5, minMet: 4.4, maxMet: 13.8, mlp: null, maxMetLimit: 10, metCap: 9 },
  { workoutType: 'Ball Sports', avgMetPerHour: 6.5, minMet: 4.2, maxMet: 9.5, mlp: null, maxMetLimit: 10, metCap: 8 },
  { workoutType: 'Skating', avgMetPerHour: null, minMet: null, maxMet: 11.36, mlp: null, maxMetLimit: 11, metCap: 7 },
  { workoutType: 'Yoga', avgMetPerHour: 7.3, minMet: 3.1, maxMet: 8.1, mlp: null, maxMetLimit: 8.1, metCap: 5.5 },
  { workoutType: 'Dance/Zumba', avgMetPerHour: 7.0, minMet: 2.2, maxMet: 8.2, mlp: null, maxMetLimit: 8.2, metCap: 8 },
  { workoutType: 'Swimming', avgMetPerHour: 6.1, minMet: 2.5, maxMet: 8.1, mlp: null, maxMetLimit: 8.1, metCap: 7 },
  { workoutType: 'Walking', avgMetPerHour: 4.5, minMet: 2.5, maxMet: 9.8, mlp: null, maxMetLimit: 7, metCap: 7 },
  { workoutType: 'General Sports', avgMetPerHour: null, minMet: null, maxMet: null, mlp: null, maxMetLimit: 10, metCap: 7 },
  { workoutType: 'Leisure Workouts', avgMetPerHour: 5.7, minMet: 3.1, maxMet: 9.2, mlp: null, maxMetLimit: 6, metCap: 4 },
  { workoutType: 'Warmups', avgMetPerHour: 5.9, minMet: 2.6, maxMet: 8.1, mlp: null, maxMetLimit: 5, metCap: 4 },
  { workoutType: 'Unidentified Workout Type', avgMetPerHour: 6.4, minMet: 4.1, maxMet: 8.4, mlp: null, maxMetLimit: 6, metCap: 6 },
  { workoutType: 'Martial Arts', avgMetPerHour: null, minMet: null, maxMet: null, mlp: null, maxMetLimit: null, metCap: 7 },
  { workoutType: 'Squash', avgMetPerHour: null, minMet: null, maxMet: null, mlp: null, maxMetLimit: null, metCap: 8 },
];

const workoutMasterRows: { workoutType: string; genericWorkoutType: string }[] = [
  ['Generic Workout', 'Gym(Strength Training)'],
  ['Workout', 'Gym(Strength Training)'],
  ['General Workout', 'Gym(Strength Training)'],
  ['Gym Workout', 'Gym(Strength Training)'],
  ['Machine Workout', 'Gym(Cardio)'],
  ['Machine Workout Misc.', 'Gym(Strength Training)'],
  ['Weight Workout', 'Gym(Strength Training)'],
  ['Total Body Weights', 'Gym(Strength Training)'],
  ['Total Body Other', 'Gym(Strength Training)'],
  ['General Total Body', 'Gym(Strength Training)'],
  ['Mat Workout', 'Gym(Strength Training)'],
  ['Home Workout', 'Gym(Strength Training)'],
  ['Health Club', 'Gym(Cardio)'],
  ['Gym Misc.', 'Gym(Strength Training)'],
  ['General Strength Training', 'Gym(Strength Training)'],
  ['Lower Body', 'Gym(Strength Training)'],
  ['Upper Body', 'Gym(Strength Training)'],
  ['Upper Body with Weights Other', 'Gym(Strength Training)'],
  ['Lower Body with Weights Other', 'Gym(Strength Training)'],
  ['Chest with Weights Other', 'Gym(Strength Training)'],
  ['Shoulders', 'Gym(Strength Training)'],
  ['Shoulders with Weights Other', 'Gym(Strength Training)'],
  ['Forearms with Weights Other', 'Gym(Strength Training)'],
  ['Abdominals', 'Gym(Strength Training)'],
  ['Abs', 'Gym(Strength Training)'],
  ['Abs Video', 'Gym(Strength Training)'],
  ['Biceps', 'Gym(Strength Training)'],
  ['Triceps with Weights Other', 'Gym(Strength Training)'],
  ['Legs', 'Gym(Strength Training)'],
  ['Kettlebell', 'Gym(Strength Training)'],
  ['Barre Workout', 'Gym(Strength Training)'],
  ['Pure Barre', 'Gym(Strength Training)'],
  ['Body Pump', 'Gym(Specialist)'],
  ['CrossFit Class', 'Gym(Specialist)'],
  ['CrossFit Video', 'Gym(Specialist)'],
  ['Orangetheory', 'Gym(Specialist)'],
  ['HIIT', 'Gym(Specialist)'],
  ['Tabata', 'Gym(Specialist)'],
  ['Insanity', 'Gym(Specialist)'],
  ['Fit Body Boot Camp', 'Gym(Strength Training)'],
  ['Gym Intervals', 'Gym(Strength Training)'],
  ['Cardiovascular (CV) Circuit Training', 'Gym(Cardio)'],
  ['Resistance Circuit Training', 'Gym(Cardio)'],
  ['Circuit Training', 'Gym(Cardio)'],
  ['Aerobic', 'Gym(Cardio)'],
  ['Aerobics', 'Gym(Cardio)'],
  ['Step Aerobics Class', 'Gym(Cardio)'],
  ['Spinning Class', 'Gym(Cardio)'],
  ['Spin', 'Gym(Cardio)'],
  ['Jump Rope', 'Gym(Cardio)'],
  ['Stair Machine', 'Gym(Cardio)'],
  ['Climbing Stairs Running', 'Gym(Cardio)'],
  ['Rowing', 'Gym(Cardio)'],
  ['Rowing Machine', 'Gym(Cardio)'],
  ['Elliptical Machine', 'Gym(Cardio)'],
  ['Elliptical Bike', 'Gym(Cardio)'],
  ['Incline Trainer', 'Gym(Cardio)'],
  ['Stationary Bike', 'Gym(Cardio)'],
  ['Indoor Bike', 'Gym(Cardio)'],
  ['Indoor Bike Trainer', 'Gym(Cardio)'],
  ['Cross Trainer', 'Gym(Specialist)'],
  ['Walk', 'Walking'],
  ['General Walk', 'Walking'],
  ['Power Walk', 'Walking'],
  ['Casual Walk', 'Walking'],
  ['Quick Walking', 'Walking'],
  ['Long Walk', 'Walking'],
  ['Brisk Walk', 'Walking'],
  ['Interval Walk', 'Walking'],
  ['Family Walk', 'Walking'],
  ['Group Walk', 'Walking'],
  ['Dog Walk', 'Walking'],
  ['Treadmill Walk', 'Walking'],
  ['Indoor Track Walk', 'Walking'],
  ['Hike', 'Walking'],
  ['General Hike', 'Walking'],
  ['Hiking Light or No Pack', 'Walking'],
  ['Hiking Medium Pack', 'Walking'],
  ['Hiking Heavy Pack', 'Walking'],
  ['Trekking', 'Walking'],
  ['Stairs', 'Walking'],
  ['Climbing Stairs Walking', 'Walking'],
  ['Climbing Stairs Indoor Walking', 'Walking'],
  ['Single Stroller Walk', 'Walking'],
  ['Double Stroller Walk', 'Walking'],
  ['Carrying Child Walk', 'Walking'],
  ['Run', 'Running'],
  ['General Run', 'Running'],
  ['Quick Run', 'Running'],
  ['Long Run', 'Running'],
  ['Trail Run', 'Running'],
  ['Easy Jog', 'Running'],
  ['Indoor Run / Jog', 'Running'],
  ['Indoor Track Run', 'Running'],
  ['Treadmill Run', 'Running'],
  ['Interval Run', 'Running'],
  ['Run Race / Event', 'Running'],
  ['Dog Run', 'Running'],
  ['Group Run', 'Running'],
  ['Bike Ride', 'Biking'],
  ['Cycling', 'Biking'],
  ['Biking', 'Biking'],
  ['Road Cycling', 'Biking'],
  ['General Road Cycling', 'Biking'],
  ['Road Cycling Indoor', 'Biking'],
  ['Hybrid Cycling', 'Biking'],
  ['General Hybrid Cycling', 'Biking'],
  ['Mountain Biking', 'Biking'],
  ['General Mountain Biking', 'Biking'],
  ['Mountain Biking Long Distance', 'Biking'],
  ['Downhill Mountain Biking', 'Biking'],
  ['Track Cycling', 'Biking'],
  ['Indoor Bike Ride', 'Biking'],
  ['Electric Bicycle', 'Biking'],
  ['Swim', 'Swimming'],
  ['Indoor Swim', 'Swimming'],
  ['Lap Swim', 'Swimming'],
  ['General Lap Swim', 'Swimming'],
  ['Open Water Swim', 'Swimming'],
  ['Group Swimming', 'Swimming'],
  ['Swimming Lessons', 'Swimming'],
  ['Swim Class / Aerobics', 'Swimming'],
  ['Football', 'Ball Sports'],
  ['Football Competitive', 'Ball Sports'],
  ['Football Practice', 'Ball Sports'],
  ['Soccer Sport', 'Ball Sports'],
  ['Indoor Soccer', 'Ball Sports'],
  ['Futsal', 'Ball Sports'],
  ['Basketball', 'Ball Sports'],
  ['Cricket', 'Ball Sports'],
  ['Indoor Cricket', 'Ball Sports'],
  ['Volleyball', 'Ball Sports'],
  ['Indoor Volleyball', 'Ball Sports'],
  ['Beach Volleyball', 'Ball Sports'],
  ['Field Hockey', 'Ball Sports'],
  ['Handball', 'Ball Sports'],
  ['Tennis', 'Racket Sports'],
  ['Tennis Doubles', 'Racket Sports'],
  ['Badminton', 'Racket Sports'],
  ['Squash', 'Squash'],
  ['PickleBall', 'Racket Sports'],
  ['Racquetball', 'Racket Sports'],
  ['Table Tennis', 'Racket Sports'],
  ['Rock Climbing', 'General Sports'],
  ['Rock Climbing Outdoor', 'General Sports'],
  ['Mountaineering', 'General Sports'],
  ['Skiing', 'General Sports'],
  ['Snorkelling', 'General Sports'],
  ['Kayak', 'General Sports'],
  ['Whitewater Rafting', 'General Sports'],
  ['Adventure Race / Event', 'General Sports'],
  ['Stand Up Paddling', 'General Sports'],
  ['Motorcycle', 'General Sports'],
  ['Sports Conditioning', 'General Sports'],
  ['Dance', 'Dance/Zumba'],
  ['Dance Class', 'Dance/Zumba'],
  ['Indoor Dance', 'Dance/Zumba'],
  ['Classical Dance', 'Dance/Zumba'],
  ['Latin Dance', 'Dance/Zumba'],
  ['Zumba', 'Dance/Zumba'],
  ['Strong by Zumba', 'Dance/Zumba'],
  ['Yoga', 'Yoga'],
  ['Yoga Class', 'Yoga'],
  ['Yoga General', 'Yoga'],
  ['Power Yoga', 'Yoga'],
  ['Ashtanga Yoga', 'Yoga'],
  ['CorePower Yoga', 'Yoga'],
  ['Stretch / Sculpt', 'Warmups'],
  ['Meditation', 'Warmups'],
  ['Recovery', 'Warmups'],
  ['Yard Work', 'Leisure Workouts'],
  ['Gardening', 'Leisure Workouts'],
  ['Farming', 'Leisure Workouts'],
  ['Cleaning (Light)', 'Leisure Workouts'],
  ['House Work', 'Leisure Workouts'],
  ['Misc Tasks (Light)', 'Leisure Workouts'],
  ['Vacuuming', 'Leisure Workouts'],
  ['Golf', 'Leisure Workouts'],
  ['Singing', 'Leisure Workouts'],
  ['Trampoline', 'Leisure Workouts'],
].map(([workoutType, genericWorkoutType]) => ({ workoutType, genericWorkoutType }));

async function main() {
  console.log('Seeding generic_workout_met...');
  await prisma.genericWorkoutMet.createMany({ data: genericWorkoutMetRows, skipDuplicates: true });

  console.log('Seeding WorkoutMaster...');
  await prisma.workoutMaster.createMany({ data: workoutMasterRows, skipDuplicates: true });

  console.log('Seed completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
